package com.riox432.civitdeck.feature.comfyui.presentation

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.riox432.civitdeck.feature.comfyui.domain.model.MaskEditorState
import com.riox432.civitdeck.feature.comfyui.domain.model.PathSegment
import com.riox432.civitdeck.feature.comfyui.domain.usecase.UploadMaskUseCase
import com.riox432.civitdeck.util.Logger
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch

/**
 * Shared ViewModel for the inpainting mask editor.
 * Manages drawing state, undo/redo, and mask upload.
 */
class MaskEditorViewModel(
    private val uploadMask: UploadMaskUseCase,
) : ViewModel() {

    private val _uiState = MutableStateFlow(MaskEditorState())
    val uiState: StateFlow<MaskEditorState> = _uiState

    fun setSourceImageUrl(url: String) {
        _uiState.update { it.copy(sourceImageUrl = url) }
    }

    fun onStrokeCompleted(points: List<Pair<Float, Float>>) {
        if (points.isEmpty()) return
        val segment = PathSegment(
            points = points,
            isEraser = _uiState.value.isEraserMode,
            brushSize = _uiState.value.brushSize,
        )
        _uiState.update {
            it.copy(
                pathSegments = it.pathSegments + segment,
                redoStack = emptyList(),
            )
        }
    }

    fun onUndo() {
        _uiState.update {
            if (it.pathSegments.isEmpty()) return@update it
            val removed = it.pathSegments.last()
            it.copy(
                pathSegments = it.pathSegments.dropLast(1),
                redoStack = it.redoStack + removed,
            )
        }
    }

    fun onRedo() {
        _uiState.update {
            if (it.redoStack.isEmpty()) return@update it
            val restored = it.redoStack.last()
            it.copy(
                pathSegments = it.pathSegments + restored,
                redoStack = it.redoStack.dropLast(1),
            )
        }
    }

    fun onClear() {
        _uiState.update {
            it.copy(
                pathSegments = emptyList(),
                redoStack = emptyList(),
                isInverted = false,
            )
        }
    }

    fun onToggleEraser() {
        _uiState.update { it.copy(isEraserMode = !it.isEraserMode) }
    }

    fun onBrushSizeChanged(size: Float) {
        val clamped = size.coerceIn(
            PathSegment.MIN_BRUSH_SIZE,
            PathSegment.MAX_BRUSH_SIZE,
        )
        _uiState.update { it.copy(brushSize = clamped) }
    }

    fun onInvertMask() {
        _uiState.update { it.copy(isInverted = !it.isInverted) }
    }

    /**
     * Upload the mask PNG bytes to the ComfyUI server.
     * [maskPngBytes] should be generated by the platform-specific encoder.
     */
    fun onUploadMask(maskPngBytes: ByteArray) {
        _uiState.update { it.copy(isUploading = true, uploadError = null) }
        viewModelScope.launch {
            try {
                val filename = uploadMask(maskPngBytes)
                _uiState.update {
                    it.copy(
                        isUploading = false,
                        uploadedMaskFilename = filename,
                    )
                }
            } catch (e: CancellationException) {
                throw e
            } catch (@Suppress("TooGenericExceptionCaught") e: Exception) {
                Logger.e(TAG, "Mask upload failed: ${e.message}")
                _uiState.update {
                    it.copy(
                        isUploading = false,
                        uploadError = e.message ?: "Upload failed",
                    )
                }
            }
        }
    }

    companion object {
        private const val TAG = "MaskEditorVM"
    }
}
