package com.riox432.civitdeck.domain.ml

import android.content.Context
import com.riox432.civitdeck.util.Logger
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.float
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonPrimitive
import kotlin.math.ln

/**
 * Minimal SentencePiece Unigram tokenizer for SigLIP-2 text encoding.
 *
 * Loads a pre-exported vocabulary from `siglip2_vocab.json` (generated by
 * `scripts/export_siglip2_text_onnx.py`) and implements the Viterbi-based
 * Unigram segmentation algorithm to split text into subword token IDs.
 *
 * This is a simplified implementation sufficient for SigLIP-2 inference:
 * - No normalization beyond lowercasing (SigLIP-2 is case-insensitive)
 * - Unigram model with log-probability scores
 * - EOS token appended, no BOS token (matching the tokenizer_config.json)
 * - Padding to max_seq_len with pad_token_id
 */
internal class SigLipTokenizer private constructor(
    private val pieces: List<String>,
    private val scores: List<Float>,
    private val pieceToId: Map<String, Int>,
    private val padTokenId: Int,
    private val eosTokenId: Int,
    private val unkTokenId: Int,
    private val maxSeqLen: Int,
    private val addEos: Boolean,
) {
    /**
     * Encodes [text] into a padded array of token IDs with length [maxSeqLen].
     *
     * Steps:
     *  1. Prepend the SentencePiece whitespace marker and lowercase
     *  2. Segment via Viterbi Unigram
     *  3. Append EOS if configured
     *  4. Truncate to maxSeqLen and pad with padTokenId
     */
    fun encode(text: String): LongArray {
        val normalized = WHITESPACE_PREFIX + text.lowercase()
        val tokenIds = segment(normalized)

        val result = LongArray(maxSeqLen) { padTokenId.toLong() }
        val effective = if (addEos) tokenIds.size + 1 else tokenIds.size
        val len = minOf(effective, maxSeqLen)

        for (i in 0 until minOf(tokenIds.size, len)) {
            result[i] = tokenIds[i].toLong()
        }
        if (addEos && len > tokenIds.size) {
            result[tokenIds.size] = eosTokenId.toLong()
        }
        return result
    }

    /**
     * Viterbi segmentation: finds the most likely subword segmentation
     * according to Unigram log-probabilities.
     *
     * For each position i in the string, compute the best score for the
     * substring ending at i by checking all possible pieces that end at i.
     */
    @Suppress("NestedBlockDepth")
    private fun segment(text: String): List<Int> {
        val n = text.length
        if (n == 0) return emptyList()

        // bestScore[i] = best log-prob score for text[0..i)
        // bestEnd[i] = the start position of the best piece ending at i
        val bestScore = FloatArray(n + 1) { Float.NEGATIVE_INFINITY }
        val bestPieceId = IntArray(n + 1) { -1 }
        val bestStart = IntArray(n + 1) { -1 }
        bestScore[0] = 0f

        for (end in 1..n) {
            val searchEnd = minOf(end, MAX_PIECE_LEN)
            for (len in 1..searchEnd) {
                val start = end - len
                if (bestScore[start] == Float.NEGATIVE_INFINITY) continue

                val piece = text.substring(start, end)
                val id = pieceToId[piece]
                if (id != null) {
                    val score = bestScore[start] + scores[id]
                    if (score > bestScore[end]) {
                        bestScore[end] = score
                        bestPieceId[end] = id
                        bestStart[end] = start
                    }
                }
            }

            // Fallback: if no piece found ending here, try byte fallback
            if (bestScore[end] == Float.NEGATIVE_INFINITY && bestScore[end - 1] > Float.NEGATIVE_INFINITY) {
                // Single character as unknown token
                bestScore[end] = bestScore[end - 1] + UNK_SCORE
                bestPieceId[end] = unkTokenId
                bestStart[end] = end - 1
            }
        }

        // Backtrace
        val result = mutableListOf<Int>()
        var pos = n
        while (pos > 0) {
            if (bestPieceId[pos] < 0) {
                // Should not happen, but handle gracefully
                result.add(0, unkTokenId)
                pos--
            } else {
                result.add(0, bestPieceId[pos])
                pos = bestStart[pos]
            }
        }
        return result
    }

    companion object {
        private const val TAG = "SigLipTokenizer"

        /** SentencePiece uses U+2581 (LOWER ONE EIGHTH BLOCK) as whitespace marker. */
        private const val WHITESPACE_PREFIX = "▁"

        /** Maximum piece length to check during Viterbi (performance bound). */
        private const val MAX_PIECE_LEN = 32

        /** Log-probability penalty for unknown tokens. */
        private val UNK_SCORE = ln(1e-10f)

        private const val VOCAB_ASSET_PATH = "ml/siglip2_vocab.json"

        /**
         * Loads the tokenizer from the app assets.
         *
         * @return the tokenizer, or null if the vocab file is missing.
         */
        @Suppress("TooGenericExceptionCaught")
        fun load(context: Context): SigLipTokenizer? {
            return try {
                val jsonStr = context.assets.open(VOCAB_ASSET_PATH).use {
                    it.bufferedReader().readText()
                }
                parseVocab(jsonStr)
            } catch (e: java.io.IOException) {
                Logger.w(TAG, "Vocab asset '$VOCAB_ASSET_PATH' missing or unreadable: ${e.message}")
                null
            } catch (e: Exception) {
                Logger.e(TAG, "Failed to parse vocab from '$VOCAB_ASSET_PATH'", e)
                null
            }
        }

        /**
         * Parses the vocabulary JSON exported by the Python script.
         *
         * Format:
         * ```json
         * {
         *   "pieces": [["<pad>", 0.0], ["<eos>", 0.0], ...],
         *   "special": {"pad": 0, "eos": 1, "bos": 2, "unk": 3},
         *   "max_seq_len": 64,
         *   "add_eos": true,
         *   "add_bos": false
         * }
         * ```
         */
        private fun parseVocab(jsonStr: String): SigLipTokenizer {
            val json = Json { ignoreUnknownKeys = true }
            val data = json.decodeFromString<VocabData>(jsonStr)

            val pieces = mutableListOf<String>()
            val scores = mutableListOf<Float>()
            val pieceToId = mutableMapOf<String, Int>()

            for ((index, entry) in data.pieces.withIndex()) {
                val arr = entry.jsonArray
                val piece = arr[0].jsonPrimitive.content
                val score = arr[1].jsonPrimitive.float
                pieces.add(piece)
                scores.add(score)
                // Only map the first occurrence (some pieces may duplicate)
                if (piece !in pieceToId) {
                    pieceToId[piece] = index
                }
            }

            return SigLipTokenizer(
                pieces = pieces,
                scores = scores,
                pieceToId = pieceToId,
                padTokenId = data.special["pad"] ?: 0,
                eosTokenId = data.special["eos"] ?: 1,
                unkTokenId = data.special["unk"] ?: 3,
                maxSeqLen = data.maxSeqLen,
                addEos = data.addEos,
            )
        }
    }
}

@Serializable
private data class VocabData(
    val pieces: List<JsonArray>,
    val special: Map<String, Int>,
    @Suppress("PropertyName", "ConstructorParameterNaming")
    val max_seq_len: Int = 64,
    @Suppress("PropertyName", "ConstructorParameterNaming")
    val add_eos: Boolean = true,
    @Suppress("PropertyName", "ConstructorParameterNaming")
    val add_bos: Boolean = false,
) {
    // Kotlin naming convention accessors
    val maxSeqLen: Int get() = max_seq_len
    val addEos: Boolean get() = add_eos
}
