package com.riox432.civitdeck.domain.ml

import ai.onnxruntime.OnnxTensor
import ai.onnxruntime.OrtEnvironment
import ai.onnxruntime.OrtSession
import android.content.Context
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.nio.LongBuffer
import kotlin.math.sqrt

/**
 * Android implementation of the SigLIP-2 text encoder, backed by ONNX Runtime.
 *
 * Loads `ml/siglip2_text_int8.onnx` and `ml/siglip2_vocab.json` from app
 * assets on first access. The tokenizer converts text to token IDs using a
 * SentencePiece Unigram model, then the ONNX session runs the text encoder
 * to produce a 768-d L2-normalised embedding.
 *
 * Both files are generated by `scripts/export_siglip2_text_onnx.py` and must
 * be placed in `androidApp/src/main/assets/ml/` before building. They are
 * excluded from version control due to size (~155 MB for the model, ~15 MB
 * for the vocab). See the script for download/generation instructions.
 *
 * The text embeddings live in the same 768-d vector space as image embeddings
 * from [ImageEmbeddingModel], enabling cross-modal similarity search.
 */
class TextEmbeddingModelImpl(
    private val context: Context,
) : TextEmbeddingModel {

    private val ortEnv: OrtEnvironment by lazy { OrtEnvironment.getEnvironment() }

    @Suppress("TooGenericExceptionCaught", "SwallowedException")
    private val session: OrtSession? by lazy {
        try {
            val bytes = context.assets.open(MODEL_ASSET_PATH).use { it.readBytes() }
            ortEnv.createSession(bytes)
        } catch (_: java.io.IOException) {
            null
        } catch (_: Exception) {
            null
        }
    }

    private val tokenizer: SigLipTokenizer? by lazy {
        SigLipTokenizer.load(context)
    }

    override val isAvailable: Boolean
        get() = session != null && tokenizer != null

    override val embeddingModelId: String = EMBEDDING_MODEL_ID

    override suspend fun embed(text: String): FloatArray {
        val ortSession = session
            ?: throw NotImplementedError(
                "SigLIP-2 text ONNX model not available — " +
                    "run scripts/export_siglip2_text_onnx.py and place files in assets/ml/",
            )
        val tok = tokenizer
            ?: throw NotImplementedError(
                "SigLIP-2 tokenizer vocab not available — " +
                    "run scripts/export_siglip2_text_onnx.py and place files in assets/ml/",
            )
        return withContext(Dispatchers.Default) {
            runInference(ortSession, tok, text)
        }
    }

    private fun runInference(
        ortSession: OrtSession,
        tok: SigLipTokenizer,
        text: String,
    ): FloatArray {
        val tokenIds = tok.encode(text)
        val inputTensor = createInputTensor(tokenIds)
        try {
            return executeAndNormalize(ortSession, inputTensor)
        } finally {
            inputTensor.close()
        }
    }

    private fun createInputTensor(tokenIds: LongArray): OnnxTensor {
        val buffer = LongBuffer.wrap(tokenIds)
        val shape = longArrayOf(BATCH_SIZE.toLong(), tokenIds.size.toLong())
        return OnnxTensor.createTensor(ortEnv, buffer, shape)
    }

    @Suppress("UNCHECKED_CAST")
    private fun executeAndNormalize(
        ortSession: OrtSession,
        inputTensor: OnnxTensor,
    ): FloatArray {
        val results = ortSession.run(mapOf(INPUT_NAME to inputTensor))
        results.use { output ->
            val poolerTensor = output.get(OUTPUT_NAME)
                .orElseThrow { IllegalStateException("Model missing '$OUTPUT_NAME' output") }
            val raw = (poolerTensor as OnnxTensor).floatBuffer
            val embedding = FloatArray(EMBEDDING_DIM)
            raw.rewind()
            raw.get(embedding)
            return l2Normalize(embedding)
        }
    }

    private fun l2Normalize(vec: FloatArray): FloatArray {
        var sumSq = 0.0f
        for (v in vec) sumSq += v * v
        val norm = sqrt(sumSq)
        if (norm > 0f) {
            for (i in vec.indices) vec[i] /= norm
        }
        return vec
    }

    private companion object {
        private const val MODEL_ASSET_PATH = "ml/siglip2_text_int8.onnx"
        private const val EMBEDDING_MODEL_ID = "siglip2-base-p16-224"
        private const val BATCH_SIZE = 1
        private const val INPUT_NAME = "input_ids"
        private const val OUTPUT_NAME = "pooler_output"
        private const val EMBEDDING_DIM = 768
    }
}
