import Shared

// MARK: - Core Domain Models
// These typealiases map the module-prefixed KMP type names (after core module split)
// back to short names used throughout the iOS codebase.

typealias AccentColor = Core_domainAccentColor
typealias BaseModel = Core_domainBaseModel
typealias CacheInfo = Core_domainCacheInfo
typealias Caption = Core_domainCaption
typealias ComfyUIConnection = Core_domainComfyUIConnection
typealias ComfyUIGenerationParams = Core_domainComfyUIGenerationParams
typealias ConnectionSecurityLevel = Core_domainConnectionSecurityLevel
typealias DiscoveredServer = Core_domainDiscoveredServer
typealias Creator = Core_domainCreator
typealias DatasetCollection = Core_domainDatasetCollection
typealias DatasetImage = Core_domainDatasetImage
typealias EmbedImageUseCase = Core_domainEmbedImageUseCase
typealias FindSimilarModelsByEmbeddingUseCase = Core_domainFindSimilarModelsByEmbeddingUseCase
typealias ImageEmbeddingModel = Core_domainImageEmbeddingModel
typealias ModelEmbeddingRepository = Core_domainModelEmbeddingRepository
typealias SigLIP2Bridge = Core_domainSigLIP2Bridge
typealias FavoriteModelSummary = Core_domainFavoriteModelSummary
typealias GenerationProgress = Core_domainGenerationProgress
typealias GenerationResult = Core_domainGenerationResult
typealias GenerationStatus = Core_domainGenerationStatus
typealias HiddenModel = Core_domainHiddenModel
typealias ImageGenerationMeta = Core_domainImageGenerationMeta
typealias ImageSource = Core_domainImageSource
typealias InteractionType = Core_domainInteractionType
typealias ImageStats = Core_domainImageStats
typealias ImageTag = Core_domainImageTag
typealias LocalModelFile = Core_domainLocalModelFile
typealias LoraSelection = Core_domainLoraSelection
typealias MatchedModelInfo = Core_domainMatchedModelInfo
typealias Model = Core_domainModel
typealias ModelCollection = Core_domainModelCollection
typealias ModelDirectory = Core_domainModelDirectory
typealias ModelFile = Core_domainModelFile
typealias ModelImage = Core_domainModelImage
typealias ModelNote = Core_domainModelNote
typealias PersonalTag = Core_domainPersonalTag
typealias ModelMode = Core_domainModelMode
typealias NavShortcut = Core_domainNavShortcut
typealias ThemeMode = Core_domainThemeMode
typealias ModelStats = Core_domainModelStats
typealias ModelType = Core_domainModelType
typealias ModelUpdate = Core_domainModelUpdate
typealias ModelVersion = Core_domainModelVersion
typealias ModelVersionStats = Core_domainModelVersionStats
typealias DuplicateGroup = Core_domainDuplicateGroup
typealias ExportFormat = Core_domainExportFormat
typealias ExportProgress = Core_domainExportProgress
typealias ExportProgressPreparing = Core_domainExportProgressPreparing
typealias ExportProgressDownloading = Core_domainExportProgressDownloading
typealias ExportProgressWritingManifest = Core_domainExportProgressWritingManifest
typealias ExportProgressCompleted = Core_domainExportProgressCompleted
typealias ExportProgressFailed = Core_domainExportProgressFailed
typealias ModelLicenseInfo = Core_domainModelLicenseInfo
typealias CivitaiLinkActivity = Core_domainCivitaiLinkActivity
typealias CivitaiLinkStatus = Core_domainCivitaiLinkStatus
typealias NsfwBlurSettings = Core_domainNsfwBlurSettings
typealias NsfwFilterLevel = Core_domainNsfwFilterLevel
typealias NsfwLevel = Core_domainNsfwLevel
typealias PageMetadata = Core_domainPageMetadata
typealias PaginatedResult = Core_domainPaginatedResult
typealias PollingInterval = Core_domainPollingInterval
typealias QueueJob = Core_domainQueueJob
typealias QueueJobStatus = Core_domainQueueJobStatus
typealias RecommendationSection = Core_domainRecommendationSection
typealias RecommendationSectionType = Core_domainRecommendationSectionType
typealias SavedPrompt = Core_domainSavedPrompt
typealias SavedSearchFilter = Core_domainSavedSearchFilter
typealias CivitaiLinkResource = Core_domainCivitaiLinkResource
typealias ExternalServerConfig = Core_domainExternalServerConfig
typealias SDWebUIConnection = Core_domainSDWebUIConnection
typealias SDWebUIGenerationParams = Core_domainSDWebUIGenerationParams
typealias SDWebUIGenerationProgressGenerating = Core_domainSDWebUIGenerationProgress.Generating
typealias SDWebUIGenerationProgressCompleted = Core_domainSDWebUIGenerationProgress.Completed
typealias SDWebUIGenerationProgressError = Core_domainSDWebUIGenerationProgress.Error
typealias SortOrder = Core_domainSortOrder
typealias Tag = Core_domainTag
typealias TimePeriod = Core_domainTimePeriod

// MARK: - Core Domain Use Cases

typealias BatchEditTagsUseCase = Core_domainBatchEditTagsUseCase
typealias DetectDuplicatesUseCase = Core_domainDetectDuplicatesUseCase
typealias EditCaptionUseCase = Core_domainEditCaptionUseCase
typealias ExportDatasetUseCase = Core_domainExportDatasetUseCase
typealias FilterByResolutionUseCase = Core_domainFilterByResolutionUseCase
typealias GetNonTrainableImagesUseCase = Core_domainGetNonTrainableImagesUseCase
typealias GetTagSuggestionsUseCase = Core_domainGetTagSuggestionsUseCase
typealias MarkImageExcludedUseCase = Core_domainMarkImageExcludedUseCase
typealias StorePHashUseCase = Core_domainStorePHashUseCase
typealias StoreImageDimensionsUseCase = Core_domainStoreImageDimensionsUseCase
typealias UpdateTrainableUseCase = Core_domainUpdateTrainableUseCase
typealias AddImageToDatasetUseCase = Core_domainAddImageToDatasetUseCase
typealias AddModelDirectoryUseCase = Core_domainAddModelDirectoryUseCase
typealias AddPersonalTagUseCase = Core_domainAddPersonalTagUseCase
typealias CheckModelUpdatesUseCase = Core_domainCheckModelUpdatesUseCase
typealias ClearBrowsingHistoryUseCase = Core_domainClearBrowsingHistoryUseCase
typealias DeleteBrowsingHistoryItemUseCase = Core_domainDeleteBrowsingHistoryItemUseCase
typealias CreateDatasetCollectionUseCase = Core_domainCreateDatasetCollectionUseCase
typealias ClearCacheUseCase = Core_domainClearCacheUseCase
typealias DeleteDatasetCollectionUseCase = Core_domainDeleteDatasetCollectionUseCase
typealias DeleteModelNoteUseCase = Core_domainDeleteModelNoteUseCase
typealias EvictCacheUseCase = Core_domainEvictCacheUseCase
typealias GetCacheInfoUseCase = Core_domainGetCacheInfoUseCase
typealias GetAllPersonalTagsUseCase = Core_domainGetAllPersonalTagsUseCase
typealias GetHiddenModelsUseCase = Core_domainGetHiddenModelsUseCase
typealias GetModelDetailUseCase = Core_domainGetModelDetailUseCase
typealias GetViewedModelIdsUseCase = Core_domainGetViewedModelIdsUseCase
typealias ObserveAccentColorUseCase = Core_domainObserveAccentColorUseCase
typealias ObserveDatasetCollectionsUseCase = Core_domainObserveDatasetCollectionsUseCase
typealias ObserveDatasetImagesUseCase = Core_domainObserveDatasetImagesUseCase
typealias ObserveThemeModeUseCase = Core_domainObserveThemeModeUseCase
typealias ObserveAmoledDarkModeUseCase = Core_domainObserveAmoledDarkModeUseCase
typealias ObserveApiKeyUseCase = Core_domainObserveApiKeyUseCase
typealias ObserveCacheSizeLimitUseCase = Core_domainObserveCacheSizeLimitUseCase
typealias ObserveDefaultSortOrderUseCase = Core_domainObserveDefaultSortOrderUseCase
typealias ObserveDefaultTimePeriodUseCase = Core_domainObserveDefaultTimePeriodUseCase
typealias ObserveFavoritesUseCase = Core_domainObserveFavoritesUseCase
typealias ObserveGridColumnsUseCase = Core_domainObserveGridColumnsUseCase
typealias ObserveIsFavoriteUseCase = Core_domainObserveIsFavoriteUseCase
typealias ObserveModelNoteUseCase = Core_domainObserveModelNoteUseCase
typealias ObserveLocalModelFilesUseCase = Core_domainObserveLocalModelFilesUseCase
typealias ObserveModelDirectoriesUseCase = Core_domainObserveModelDirectoriesUseCase
typealias ObserveNetworkStatusUseCase = Core_domainObserveNetworkStatusUseCase
typealias ObserveNotificationsEnabledUseCase = Core_domainObserveNotificationsEnabledUseCase
typealias ObserveNsfwBlurSettingsUseCase = Core_domainObserveNsfwBlurSettingsUseCase
typealias ObserveCustomNavShortcutsUseCase = Core_domainObserveCustomNavShortcutsUseCase
typealias ObserveNsfwFilterUseCase = Core_domainObserveNsfwFilterUseCase
typealias ObserveOfflineCacheEnabledUseCase = Core_domainObserveOfflineCacheEnabledUseCase
typealias ObserveOwnedModelHashesUseCase = Core_domainObserveOwnedModelHashesUseCase
typealias ObservePollingIntervalUseCase = Core_domainObservePollingIntervalUseCase
typealias ObservePersonalTagsUseCase = Core_domainObservePersonalTagsUseCase
typealias ObservePowerUserModeUseCase = Core_domainObservePowerUserModeUseCase
typealias ObserveQualityThresholdUseCase = Core_domainObserveQualityThresholdUseCase
typealias SetQualityThresholdUseCase = Core_domainSetQualityThresholdUseCase
typealias ObserveSeenTutorialVersionUseCase = Core_domainObserveSeenTutorialVersionUseCase
typealias RemoveImageFromDatasetUseCase = Core_domainRemoveImageFromDatasetUseCase
typealias RemoveModelDirectoryUseCase = Core_domainRemoveModelDirectoryUseCase
typealias RemovePersonalTagUseCase = Core_domainRemovePersonalTagUseCase
typealias RenameDatasetCollectionUseCase = Core_domainRenameDatasetCollectionUseCase
typealias SaveModelNoteUseCase = Core_domainSaveModelNoteUseCase
typealias ScanModelDirectoriesUseCase = Core_domainScanModelDirectoriesUseCase
typealias SearchModelsByTagUseCase = Core_domainSearchModelsByTagUseCase
typealias SetAccentColorUseCase = Core_domainSetAccentColorUseCase
typealias SetAmoledDarkModeUseCase = Core_domainSetAmoledDarkModeUseCase
typealias SetApiKeyUseCase = Core_domainSetApiKeyUseCase
typealias SetCacheSizeLimitUseCase = Core_domainSetCacheSizeLimitUseCase
typealias SetDefaultSortOrderUseCase = Core_domainSetDefaultSortOrderUseCase
typealias SetDefaultTimePeriodUseCase = Core_domainSetDefaultTimePeriodUseCase
typealias SetCustomNavShortcutsUseCase = Core_domainSetCustomNavShortcutsUseCase
typealias SetGridColumnsUseCase = Core_domainSetGridColumnsUseCase
typealias SetNotificationsEnabledUseCase = Core_domainSetNotificationsEnabledUseCase
typealias SetNsfwBlurSettingsUseCase = Core_domainSetNsfwBlurSettingsUseCase
typealias SetNsfwFilterUseCase = Core_domainSetNsfwFilterUseCase
typealias SetOfflineCacheEnabledUseCase = Core_domainSetOfflineCacheEnabledUseCase
typealias SetPollingIntervalUseCase = Core_domainSetPollingIntervalUseCase
typealias SetPowerUserModeUseCase = Core_domainSetPowerUserModeUseCase
typealias SetSeenTutorialVersionUseCase = Core_domainSetSeenTutorialVersionUseCase
typealias ToggleFavoriteUseCase = Core_domainToggleFavoriteUseCase
typealias TrackModelViewUseCase = Core_domainTrackModelViewUseCase
typealias ValidateApiKeyUseCase = Core_domainValidateApiKeyUseCase
typealias VerifyModelHashUseCase = Core_domainVerifyModelHashUseCase
typealias GetBrowsingStatsUseCase = Core_domainGetBrowsingStatsUseCase
typealias ObserveRecentlyViewedUseCase = Core_domainObserveRecentlyViewedUseCase
typealias RecentlyViewedModel = Core_domainRecentlyViewedModel
typealias BrowsingStats = Core_domainBrowsingStats
typealias DailyViewCount = Core_domainDailyViewCount
typealias CategoryStat = Core_domainCategoryStat
typealias DownloadStatus = Core_domainDownloadStatus
typealias ModelDownload = Core_domainModelDownload
typealias EnqueueDownloadUseCase = Core_domainEnqueueDownloadUseCase
typealias ObserveModelDownloadsUseCase = Core_domainObserveModelDownloadsUseCase
typealias CancelDownloadUseCase = Core_domainCancelDownloadUseCase
typealias ObserveDownloadsUseCase = Core_domainObserveDownloadsUseCase
typealias DeleteDownloadUseCase = Core_domainDeleteDownloadUseCase
typealias ClearCompletedDownloadsUseCase = Core_domainClearCompletedDownloadsUseCase
typealias PauseDownloadUseCase = Core_domainPauseDownloadUseCase
typealias ResumeDownloadUseCase = Core_domainResumeDownloadUseCase
typealias VerifyDownloadHashUseCase = Core_domainVerifyDownloadHashUseCase
typealias ModelDownloadRepository = Core_domainModelDownloadRepository
typealias FeedItem = Core_domainFeedItem
typealias FollowedCreator = Core_domainFollowedCreator
typealias FollowCreatorUseCase = Core_domainFollowCreatorUseCase
typealias UnfollowCreatorUseCase = Core_domainUnfollowCreatorUseCase
typealias IsFollowingCreatorUseCase = Core_domainIsFollowingCreatorUseCase
typealias GetCreatorFeedUseCase = Core_domainGetCreatorFeedUseCase
typealias GetUnreadFeedCountUseCase = Core_domainGetUnreadFeedCountUseCase
typealias MarkFeedReadUseCase = Core_domainMarkFeedReadUseCase
typealias GetFollowedCreatorsUseCase = Core_domainGetFollowedCreatorsUseCase
typealias GetModelReviewsUseCase = Core_domainGetModelReviewsUseCase
typealias GetRatingTotalsUseCase = Core_domainGetRatingTotalsUseCase
typealias RatingTotals = Core_domainRatingTotals
typealias ResourceReview = Core_domainResourceReview
typealias ReviewPage = Core_domainReviewPage
typealias SubmitReviewUseCase = Core_domainSubmitReviewUseCase
typealias BackupCategory = Core_domainBackupCategory
typealias RestoreStrategy = Core_domainRestoreStrategy
typealias CreateBackupUseCase = Core_domainCreateBackupUseCase
typealias RestoreBackupUseCase = Core_domainRestoreBackupUseCase
typealias ParseBackupUseCase = Core_domainParseBackupUseCase
typealias InstalledPlugin = Core_domainInstalledPlugin
typealias InstalledPluginState = Core_domainInstalledPluginState
typealias InstalledPluginType = Core_domainInstalledPluginType
typealias ActivatePluginUseCase = Core_domainActivatePluginUseCase
typealias DeactivatePluginUseCase = Core_domainDeactivatePluginUseCase
typealias GetPluginConfigUseCase = Core_domainGetPluginConfigUseCase
typealias InstallPluginUseCase = Core_domainInstallPluginUseCase
typealias ObserveInstalledPluginsUseCase = Core_domainObserveInstalledPluginsUseCase
typealias UninstallPluginUseCase = Core_domainUninstallPluginUseCase
typealias UpdatePluginConfigUseCase = Core_domainUpdatePluginConfigUseCase
typealias ModelUpdateNotification = Core_domainModelUpdateNotification
typealias UpdateSource = Core_domainUpdateSource
typealias GetModelUpdateNotificationsUseCase = Core_domainGetModelUpdateNotificationsUseCase
typealias GetUnreadNotificationCountUseCase = Core_domainGetUnreadNotificationCountUseCase
typealias MarkNotificationReadUseCase = Core_domainMarkNotificationReadUseCase
typealias MarkAllNotificationsReadUseCase = Core_domainMarkAllNotificationsReadUseCase
typealias CheckAndStoreModelUpdatesUseCase = Core_domainCheckAndStoreModelUpdatesUseCase
typealias ShareHashtag = Core_domainShareHashtag
typealias AddShareHashtagUseCase = Core_domainAddShareHashtagUseCase
typealias ObserveShareHashtagsUseCase = Core_domainObserveShareHashtagsUseCase
typealias RemoveShareHashtagUseCase = Core_domainRemoveShareHashtagUseCase
typealias ToggleShareHashtagUseCase = Core_domainToggleShareHashtagUseCase

// MARK: - Core Plugin Types

typealias PluginExportFormat = Core_pluginPluginExportFormat
typealias PluginExportProgress = Core_pluginPluginExportProgress
typealias ExportFormatPlugin = Core_pluginExportFormatPlugin
typealias ThemePlugin = Core_pluginThemePlugin
typealias ThemeColorScheme = Core_pluginThemeColorScheme
typealias PluginState = Core_pluginPluginState
typealias PluginManifest = Core_pluginPluginManifest

typealias ReviewSortOrder = Core_domainReviewSortOrder

// MARK: - Feature: Collections (shared use cases in core-domain)

typealias AddModelToCollectionUseCase = Core_domainAddModelToCollectionUseCase
typealias BulkMoveModelsUseCase = Feature_collectionsBulkMoveModelsUseCase
typealias BulkRemoveModelsUseCase = Feature_collectionsBulkRemoveModelsUseCase
typealias CreateCollectionUseCase = Core_domainCreateCollectionUseCase
typealias DeleteCollectionUseCase = Feature_collectionsDeleteCollectionUseCase
typealias ObserveCollectionModelsUseCase = Feature_collectionsObserveCollectionModelsUseCase
typealias ObserveCollectionsUseCase = Core_domainObserveCollectionsUseCase
typealias ObserveModelCollectionsUseCase = Core_domainObserveModelCollectionsUseCase
typealias RemoveModelFromCollectionUseCase = Core_domainRemoveModelFromCollectionUseCase
typealias RenameCollectionUseCase = Feature_collectionsRenameCollectionUseCase

// MARK: - Feature: Search (shared use cases in core-domain)

typealias AddExcludedTagUseCase = Core_domainAddExcludedTagUseCase
typealias AddSearchHistoryUseCase = Feature_searchAddSearchHistoryUseCase
typealias ClearSearchHistoryUseCase = Core_domainClearSearchHistoryUseCase
typealias DeleteSearchHistoryItemUseCase = Feature_searchDeleteSearchHistoryItemUseCase
typealias GetDiscoveryModelsUseCase = Feature_searchGetDiscoveryModelsUseCase
typealias GetExcludedTagsUseCase = Core_domainGetExcludedTagsUseCase
typealias GetHiddenModelIdsUseCase = Feature_searchGetHiddenModelIdsUseCase
typealias GetModelsUseCase = Feature_searchGetModelsUseCase
typealias MultiSourceSearchUseCase = Feature_searchMultiSourceSearchUseCase
typealias MultiSourceSearchResult = Feature_searchMultiSourceSearchResult
typealias GetRecommendationsUseCase = Feature_searchGetRecommendationsUseCase
typealias TrackRecommendationClickUseCase = Feature_searchTrackRecommendationClickUseCase
typealias DeleteSavedSearchFilterUseCase = Feature_searchDeleteSavedSearchFilterUseCase
typealias HideModelUseCase = Feature_searchHideModelUseCase
typealias ObserveSavedSearchFiltersUseCase = Feature_searchObserveSavedSearchFiltersUseCase
typealias ObserveSearchHistoryUseCase = Feature_searchObserveSearchHistoryUseCase
typealias RemoveExcludedTagUseCase = Core_domainRemoveExcludedTagUseCase
typealias SaveSearchFilterUseCase = Feature_searchSaveSearchFilterUseCase
typealias SwipeDiscoveryViewModel = Feature_searchSwipeDiscoveryViewModel
typealias SwipeDiscoveryState = Feature_searchSwipeDiscoveryState
typealias BrowsingHistoryViewModel = Feature_searchBrowsingHistoryViewModel
typealias BrowsingHistoryUiState = Feature_searchBrowsingHistoryUiState
typealias UnhideModelUseCase = Core_domainUnhideModelUseCase

// MARK: - Feature: Detail

typealias SharedModelDetailViewModel = Feature_detailModelDetailViewModel
typealias SharedModelDetailUiState = Feature_detailModelDetailUiState

// MARK: - Feature: Gallery

typealias EnrichModelImagesUseCase = Core_domainEnrichModelImagesUseCase
typealias GetImagesUseCase = Feature_galleryGetImagesUseCase
typealias ImageGalleryViewModel = Feature_galleryImageGalleryViewModel
typealias ImageGalleryUiState = Feature_galleryImageGalleryUiState

// MARK: - Feature: Prompts (shared use cases in core-domain)

typealias AutoSavePromptUseCase = Core_domainAutoSavePromptUseCase
typealias DeleteSavedPromptUseCase = Feature_promptsDeleteSavedPromptUseCase
typealias ObserveSavedPromptsUseCase = Feature_promptsObserveSavedPromptsUseCase
typealias ObserveTemplatesUseCase = Feature_promptsObserveTemplatesUseCase
typealias SavePromptUseCase = Core_domainSavePromptUseCase
typealias SearchSavedPromptsUseCase = Feature_promptsSearchSavedPromptsUseCase
typealias ToggleTemplateUseCase = Feature_promptsToggleTemplateUseCase

// MARK: - Feature: Creator

typealias GetCreatorModelsUseCase = Feature_creatorGetCreatorModelsUseCase

// MARK: - Feature: ComfyUI — Workflow Templates

typealias ComfyUIGeneratedImage = Core_domainComfyUIGeneratedImage
typealias ComfyUIGenerationMeta = Core_domainComfyUIGenerationMeta
typealias WorkflowTemplate = Core_domainWorkflowTemplate
typealias WorkflowTemplateType = Core_domainWorkflowTemplateType
typealias WorkflowTemplateCategory = Core_domainWorkflowTemplateCategory
typealias TemplateVariable = Core_domainTemplateVariable
typealias TemplateVariableType = Core_domainTemplateVariableType
typealias GetWorkflowTemplatesUseCase = Feature_comfyuiGetWorkflowTemplatesUseCase
typealias SaveWorkflowTemplateUseCase = Feature_comfyuiSaveWorkflowTemplateUseCase
typealias DeleteWorkflowTemplateUseCase = Feature_comfyuiDeleteWorkflowTemplateUseCase
typealias ExportWorkflowTemplateUseCase = Feature_comfyuiExportWorkflowTemplateUseCase
typealias ImportWorkflowTemplateUseCase = Feature_comfyuiImportWorkflowTemplateUseCase
typealias ApplyWorkflowTemplateUseCase = Feature_comfyuiApplyWorkflowTemplateUseCase

// MARK: - Feature: ComfyHub

typealias ComfyHubWorkflow = Core_domainComfyHubWorkflow
typealias ComfyHubCategory = Core_domainComfyHubCategory
typealias ComfyHubSortOrder = Core_domainComfyHubSortOrder
typealias SearchComfyHubWorkflowsUseCase = Feature_comfyuiSearchComfyHubWorkflowsUseCase
typealias GetComfyHubWorkflowDetailUseCase = Feature_comfyuiGetComfyHubWorkflowDetailUseCase
typealias ImportComfyHubWorkflowUseCase = Feature_comfyuiImportComfyHubWorkflowUseCase

// MARK: - Feature: External Server

typealias ServerImage = Feature_externalserverServerImage
typealias PaginatedImagesResponse = Feature_externalserverPaginatedImagesResponse
typealias ExternalServerImageFilters = Feature_externalserverExternalServerImageFilters
typealias ObserveExternalServerConfigsUseCase = Feature_externalserverObserveExternalServerConfigsUseCase
typealias ObserveActiveExternalServerConfigUseCase = Feature_externalserverObserveActiveExternalServerConfigUseCase
typealias SaveExternalServerConfigUseCase = Feature_externalserverSaveExternalServerConfigUseCase
typealias DeleteExternalServerConfigUseCase = Feature_externalserverDeleteExternalServerConfigUseCase
typealias ActivateExternalServerConfigUseCase = Feature_externalserverActivateExternalServerConfigUseCase
typealias TestExternalServerConnectionUseCase = Feature_externalserverTestExternalServerConnectionUseCase
typealias GetExternalServerCapabilitiesUseCase = Feature_externalserverGetExternalServerCapabilitiesUseCase
typealias GetExternalServerImagesUseCase = Feature_externalserverGetExternalServerImagesUseCase
typealias ServerCapabilities = Feature_externalserverServerCapabilities
typealias GenerationOption = Feature_externalserverGenerationOption
typealias GenerationOptionType = Feature_externalserverGenerationOptionType
typealias GenerationChoice = Feature_externalserverGenerationChoice
typealias GenerationJob = Feature_externalserverGenerationJob
typealias GenerationJobStatus = Feature_externalserverGenerationJobStatus
typealias GetGenerationOptionsUseCase = Feature_externalserverGetGenerationOptionsUseCase
typealias GetDependentChoicesUseCase = Feature_externalserverGetDependentChoicesUseCase
typealias ExecuteGenerationUseCase = Feature_externalserverExecuteGenerationUseCase
typealias GetGenerationStatusUseCase = Feature_externalserverGetGenerationStatusUseCase
typealias DeleteServerImagesUseCase = Feature_externalserverDeleteServerImagesUseCase

// MARK: - Settings VMs (moved from shared to feature-settings)
typealias AuthSettingsViewModel = Feature_settingsAuthSettingsViewModel
typealias ContentFilterSettingsViewModel = Feature_settingsContentFilterSettingsViewModel
typealias DisplaySettingsViewModel = Feature_settingsDisplaySettingsViewModel
typealias StorageSettingsViewModel = Feature_settingsStorageSettingsViewModel
typealias AppBehaviorSettingsViewModel = Feature_settingsAppBehaviorSettingsViewModel

typealias AuthSettingsUiState = Feature_settingsAuthSettingsUiState
typealias ContentFilterSettingsUiState = Feature_settingsContentFilterSettingsUiState
typealias DisplaySettingsUiState = Feature_settingsDisplaySettingsUiState
typealias StorageSettingsUiState = Feature_settingsStorageSettingsUiState
typealias AppBehaviorSettingsUiState = Feature_settingsAppBehaviorSettingsUiState
typealias BackupViewModel = Feature_settingsBackupViewModel
typealias BackupUiState = Feature_settingsBackupUiState

// MARK: - ComfyHub VMs (moved from shared to feature-comfyui)
typealias ComfyHubBrowserViewModel = Feature_comfyuiComfyHubBrowserViewModel
typealias ComfyHubBrowserUiState = Feature_comfyuiComfyHubBrowserUiState
typealias ComfyHubDetailViewModel = Feature_comfyuiComfyHubDetailViewModel
typealias ComfyHubDetailUiState = Feature_comfyuiComfyHubDetailUiState

// MARK: - Dataset VMs (moved from shared to feature-collections)
typealias DatasetListViewModel = Feature_collectionsDatasetListViewModel

typealias DatasetDetailViewModel = Feature_collectionsDatasetDetailViewModel

typealias BatchTagEditorViewModel = Feature_collectionsBatchTagEditorViewModel

typealias ExportWithPluginUseCase = Feature_collectionsExportWithPluginUseCase
typealias GetAvailableExportFormatsUseCase = Feature_collectionsGetAvailableExportFormatsUseCase

// MARK: - Search VMs (moved from shared to feature-search)
typealias TextSearchViewModel = Feature_searchTextSearchViewModel
typealias TextSearchUiState = Feature_searchTextSearchUiState
typealias SimilarModelsViewModel = Feature_searchSimilarModelsViewModel
typealias SimilarModelsUiState = Feature_searchSimilarModelsUiState

// MARK: - Gallery VMs (moved from shared to feature-gallery)
typealias DownloadQueueViewModel = Feature_galleryDownloadQueueViewModel
typealias DownloadQueueUiState = Feature_galleryDownloadQueueUiState
typealias ModelFileBrowserViewModel = Feature_galleryModelFileBrowserViewModel
typealias ModelFileBrowserUiState = Feature_galleryModelFileBrowserUiState
typealias ShareViewModel = Feature_galleryShareViewModel

typealias GestureTutorialViewModel = Feature_galleryGestureTutorialViewModel
typealias AnalyticsViewModel = Feature_galleryAnalyticsViewModel
typealias AnalyticsUiState = Feature_galleryAnalyticsUiState
typealias NotificationCenterViewModel = Feature_galleryNotificationCenterViewModel
typealias NotificationCenterUiState = Feature_galleryNotificationCenterUiState


// MARK: - Creator VMs (moved from shared to feature-creator)
typealias FeedViewModel = Feature_creatorFeedViewModel
typealias FeedUiState = Feature_creatorFeedUiState

// MARK: - ModelImage Swift Extensions
// Kotlin extension functions are not exported to Swift, so we mirror them here.

extension Core_domainModelImage {
    /// Returns a CDN URL resized to the given width.
    /// CivitAI CDN format: .../xG1nkqKTMzGDvpLrqFT7WA/{uuid}/width={size}/{filename}
    func thumbnailUrl(width: Int) -> String? {
        guard !url.isEmpty else { return nil }
        guard url.contains("image.civitai.com") else { return url }
        var parts = url.split(separator: "/", omittingEmptySubsequences: false).map(String.init)
        if let widthIdx = parts.firstIndex(where: { $0.hasPrefix("width=") }) {
            parts[widthIdx] = "width=\(width)"
        } else if parts.count > 5 {
            parts.insert("width=\(width)", at: 5)
        }
        return parts.joined(separator: "/")
    }
}
